SchoolApp/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")),
    path('teacher/', include("teacher.urls")),
    path('student/', include("student.urls")),
    path('staff/', include("staff.urls")),
]

urlpatterns += staticfiles_urlpatterns()

accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('user_redirect', views.user_redirect, name='user_redirect'),
    path('logout', views.logout, name='logout'),
]

staff/urls.py
from django.urls import path

from . import views

app_name = "staff"

urlpatterns = [
    path('', views.index, name='index'),
]

student/urls.py
from django.urls import path

from . import views

app_name = "student"

urlpatterns = [
    path('', views.index, name='index'),
    path('view_attendance', views.view_attendance, name='view_attendance'),

]

student/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from teacher.models import Standard


class Enrollment(models.Model):
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE)
    student = models.ForeignKey(User, limit_choices_to={'extendeduser__type': 'Student'}, on_delete=models.CASCADE)
    enrolled_on = models.DateTimeField(default=timezone.now)
    enrolled_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='enrolled_by')

student/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET, require_POST

from accounts.helpers import exception_msg
from student.helpers import get_student_class
from student.view_attendance_helper import ViewAttendance


@login_required(login_url='/')
@require_GET
def index(request):
    student_class = get_student_class(request.user)
    context = {
        "standard": student_class
    }
    return render(request, "student/index.html", context)


@login_required(login_url='/')
@require_POST
def view_attendance(request):
    try:
        date = request.POST["date"]
        standard = request.POST["standard"]

        view_helper = ViewAttendance(request.user, date, standard)
        records = view_helper.get_attendance_for_date()

        return JsonResponse({"status": True, "records": records})
    except Exception as e:
        exception_msg("view_attendance", e)
        return JsonResponse({"status": False, "msg": "Something went wrong while getting records. Please try again."})

templates/student/index.html
{% extends "utils/base.html" %}

{% block title %}
    Student Dashboard
{% endblock %}

{% block navbar %}
    {% include "student/navbar.html" %}
{% endblock %}

{% block content %}
    <div class="row" style="padding: 1rem">
        <div class="col">
            {% if standard %}
                <div class="alert alert-info">
                    <p>
                        Class: {{ standard.class_name }}<br>
                        Subjects: {% for sub in standard.subjects.all %}<span class="badge bg-info text-dark">{{ sub.name }}</span>&nbsp;&nbsp;{% endfor %}
                    </p>
                </div>
            {% else %}
                <div class="alert alert-info">
                    <p>
                        Not enrolled in any class
                    </p>
                </div>
            {% endif %}
        </div>
    </div>

    <div id="view_attendance_div">
        <div class="row">
            <div class="col">
                <label class="form-label" for="month_attendance">View Attendance for: </label>
                <input type="month" class="form-control" id="month_attendance" v-model="selected_date">
            </div>
        </div>

        <div class="row" v-show="fetching_data">
            <div class="col">
                <div class="alert alert-info">
                    <i class="fa fa-spinner fa-spin"></i>&nbsp;Fetching data
                </div>
            </div>
        </div>

        <div class="row" v-show="!fetching_data && selected_date !== ''">
            <div class="col">
                <table class="table table-hover">
                    <thead>
                        <th>Date</th>
                        <th>Status</th>
                    </thead>
                    <tbody>
                        <tr v-for="record in records">
                            <td>
                                {% templatetag openvariable %}
                                     record.date
                                {% templatetag closevariable %}
                            </td>
                            <td>
                                {% templatetag openvariable %}
                                    record.status
                                {% templatetag closevariable %}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block custom_scripts %}
    {% include "student/scripts/view_attendance_app.html" %}
{% endblock %}

templates/student/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
         <div class="container">
      <a class="navbar-brand" href="{% url 'accounts:login' %}">MSB School</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:user_redirect' %}">Home</a>
          </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">View Attendance</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>

        </ul>
      </div>
         </div>
    </nav>