SchoolApp/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")),
    path('teacher/', include("teacher.urls")),
    path('student/', include("student.urls")),
    path('staff/', include("staff.urls")),
]

urlpatterns += staticfiles_urlpatterns()

staff/urls.py
from django.urls import path

from . import views

app_name = "staff"

urlpatterns = [
    path('', views.index, name='index'),
]

teacher/urls.py
from django.urls import path

from . import views

app_name = "teacher"

urlpatterns = [
    path('', views.index, name='index'),
    path('get_not_enrolled_students', views.get_not_enrolled_students, name='get_not_enrolled_students'),
    path('enroll_student', views.enroll_student, name='enroll_student'),
    path('view_enrolled_students', views.view_enrolled_students, name='view_enrolled_students'),
    path('get_attendance', views.get_attendance, name='get_attendance'),
    path('save_attendance', views.save_student_attendance, name='save_attendance'),
]

teacher/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models


class Subject(models.Model):
    name = models.CharField(max_length=200, primary_key=True)


class Standard(models.Model):   # Stores classes
    class_name = models.CharField(max_length=200, primary_key=True)
    teacher = models.ManyToManyField(User, limit_choices_to={'extendeduser__type': 'Teacher'})
    subjects = models.ManyToManyField(Subject)


class AttendanceRecord(models.Model):
    day = models.DateField()
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    present = models.BooleanField(blank=True, null=True)

teacher/views.py
import json

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET, require_POST

from accounts.helpers import exception_msg
from student.enroll_student import EnrollStudent
from student.helpers import not_enrolled_students
from teacher.attendance_helper import MarkStudentAttendance
from teacher.helpers import get_classes_taught_by_teacher


@login_required(login_url='/')
def index(request):
    context = {
        "classes": get_classes_taught_by_teacher(request.user),
    }
    return render(request, "teacher/index.html", context)


@login_required(login_url='/')
@require_GET
def get_not_enrolled_students(request):
    try:
        student_list = []
        for student in not_enrolled_students():
            student_list.append({
                "name": student.get_full_name(),
                "id": student.id,
                "email": student.email,
            })

        return JsonResponse({"status": True, "student_list": student_list})
    except Exception as e:
        exception_msg("get_not_enrolled_students", e)
        return JsonResponse({"status": False, "msg": "Something went wrong while getting student information."})


@login_required(login_url='/')
@require_POST
def enroll_student(request):
    try:
        standard_name = request.POST['standard']
        student_id = request.POST['student_id']

        enrollment_helper = EnrollStudent(request.user, standard_name=standard_name)
        enrollment_helper.enroll_student(student_id)
        return JsonResponse({"status": True})
    except Exception as e:
        exception_msg("enroll_student", e)
        return JsonResponse({"status": False, "msg": "Something went wrong while enrolling student. "
                                                     "Please try again."})


@login_required(login_url='/')
@require_POST
def view_enrolled_students(request):
    try:
        standard_name = request.POST['standard']

        enrollment_helper = EnrollStudent(request.user, standard_name=standard_name)
        enrolled_students = enrollment_helper.get_enrolled_students()

        return JsonResponse({"status": True, "enrolled_students": enrolled_students})
    except Exception as e:
        exception_msg("view_enrolled_students", e)
        return JsonResponse({"status": False, "msg": "Something went wrong while fetching enrolled students. "
                                                     "Please try again."})


@login_required(login_url='/')
@require_POST
def get_attendance(request):
    try:
        standard_name = request.POST['standard']
        date = request.POST['date']

        attendance_helper = MarkStudentAttendance(request.user, standard_name, date)
        return JsonResponse({"status": True, "records": attendance_helper.get_attendance()})
    except Exception as e:
        exception_msg("get_attendance", e)
        return JsonResponse({"status": False, "msg": "Something went wrong while fetching attendance records. "
                                                     "Please try again."})


@login_required(login_url='/')
@require_POST
def save_student_attendance(request):
    try:
        records = json.loads(request.POST['records'])
        standard_name = request.POST['standard']
        date = request.POST['date']

        attendance_helper = MarkStudentAttendance(request.user, standard_name, date)
        attendance_helper.save_attendance(records)

        return JsonResponse({"status": True})
    except Exception as e:
        exception_msg("save_student_attendance", e)
        return JsonResponse({"status": False, "msg": "Could not save attendance. Please try again."})

templates/teacher/scripts/attendance_app.html
<script>

let attendance_app = Vue.createApp({
    data() {
        return {
            standard: "",
            selected_date: "",

            fetching_students: false,
            records: [],
        }
    },
    methods: {
        get_attendance() {
            let formData = new FormData();
            formData.append("date", this.selected_date);
            formData.append("standard", this.standard);

            post_request(
                "{% url 'teacher:get_attendance' %}",
                formData,
                (resp) => {this.records = resp['records'];},
                (resp) => {warning_toast(resp['msg']);}
            );
        },
        save_attendance() {
            let formData = new FormData();
            formData.append("date", this.selected_date);
            formData.append("standard", this.standard);
            formData.append("records", JSON.stringify(this.records));

            post_request(
                "{% url 'teacher:save_attendance' %}",
                formData,
                (resp) => {success_toast("Attendance saved!");},
                (resp) => {warning_toast(resp['msg']);}
            );
        },
    },
    watch: {
        selected_date(newVal, oldVal) {
            this.get_attendance();
        },
    },
}).mount("#attendance_modal");
</script>

templates/teacher/scripts/enroll_student.html
<script>
let enroll_app = Vue.createApp({
    data() {
        return {
            students: [],
            fetching_students: false,

            selected_student: "-",
            standard_name: "",

            enrolled_students: [],
        }
    },
    methods: {
        get_not_enrolled_students() {
            this.fetching_students = true;
            get_request(
                "{% url 'teacher:get_not_enrolled_students' %}",
                null,
                (resp) => {this.students = resp["student_list"]; this.fetching_students = false},
                (resp) => {warning_toast(resp['msg']); this.fetching_students = false;}
            )
        },

        enroll_student(elementRef) {
            elementRef.srcElement.innerHTML = `<i class="fa fa-spinner fa-spin"></i> Enrolling...`;
            let formData = new FormData();
            formData.append("standard", this.standard_name);
            formData.append("student_id", this.selected_student);

            post_request(
                "{% url 'teacher:enroll_student' %}",
                formData,
                (resp) => {
                    success_alert("Enrollment Successful",
                        `Selected student was enrolled in class ${this.standard_name}.`);
                    this.get_not_enrolled_students();
                    elementRef.srcElement.innerHTML = "Enroll Student";
                    this.selected_student = '-';
                },
                (resp) => {
                    warning_toast(resp['msg']);
                    elementRef.srcElement.innerHTML = "Enroll Student";
                }
            );
        },

        get_enrolled_students() {
            this.enrolled_students = [];
            let formData = new FormData();
            formData.append("standard", this.standard_name);

            post_request(
                "{% url 'teacher:view_enrolled_students' %}",
                formData,
                (resp) => {this.enrolled_students = resp['enrolled_students'];},
                (resp) => {warning_toast(resp['msg']);}
            )
        },

    },
}).mount("#modals_div");

enroll_app.get_not_enrolled_students();
</script>