SchoolApp/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")),
    path('teacher/', include("teacher.urls")),
    path('student/', include("student.urls")),
    path('staff/', include("staff.urls")),
]

urlpatterns += staticfiles_urlpatterns()

staff/urls.py
from django.urls import path

from . import views

app_name = "staff"

urlpatterns = [
    path('', views.index, name='index'),
]

student/urls.py
from django.urls import path

from . import views

app_name = "student"

urlpatterns = [
    path('', views.index, name='index'),
    path('view_attendance', views.view_attendance, name='view_attendance'),

]

student/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from teacher.models import Standard


class Enrollment(models.Model):
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE)
    student = models.ForeignKey(User, limit_choices_to={'extendeduser__type': 'Student'}, on_delete=models.CASCADE)
    enrolled_on = models.DateTimeField(default=timezone.now)
    enrolled_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='enrolled_by')

student/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET, require_POST

from accounts.helpers import exception_msg
from student.helpers import get_student_class
from student.view_attendance_helper import ViewAttendance


@login_required(login_url='/')
@require_GET
def index(request):
    student_class = get_student_class(request.user)
    context = {
        "standard": student_class
    }
    return render(request, "student/index.html", context)


@login_required(login_url='/')
@require_POST
def view_attendance(request):
    try:
        date = request.POST["date"]
        standard = request.POST["standard"]

        view_helper = ViewAttendance(request.user, date, standard)
        records = view_helper.get_attendance_for_date()

        return JsonResponse({"status": True, "records": records})
    except Exception as e:
        exception_msg("view_attendance", e)
        return JsonResponse({"status": False, "msg": "Something went wrong while getting records. Please try again."})

templates/student/scripts/view_attendance_app.html
<script>

let view_attendance_app = Vue.createApp({
    data() {
        return {
            standard: {% if standard %}"{{ standard.class_name }}"{% else %}""{% endif %},
            selected_date: "",
            fetching_data: false,
            records: [],
        }
    },
    methods: {
        get_records() {
            this.fetching_data = true;
            let formData = new FormData();
            formData.append("standard", this.standard);
            formData.append("date", this.selected_date);

            post_request(
                "{% url 'student:view_attendance' %}",
                formData,
                (resp) => {this.fetching_data = false; this.records = resp['records'];},
                (resp) => {this.fetching_data = false; warning_toast(resp['msg']);}
            )
        },
    },
    watch: {
        selected_date(newVal, oldVal) {
            this.get_records();
        }
    }
}).mount("#view_attendance_div");
</script>